#!/usr/bin/env python3
"""Generate roms_embedded.c: the recognised BIOS / High Score Cart ROMs in a
directory, or nothing at all.

The Atari 7800 BIOSes and the High Score Cart's ROM are copyrighted Atari
firmware and are not redistributed by this project (COMPLIANCE.md). --none
is therefore the SHIPPING configuration, not an error path: it emits an
empty table, and the console boots the FujiNet cartridge directly through
MAME's "none" BIOS.

With a directory (WITH_A7800_ROMS=ON, a developer build), every file in it
whose size and CRC-32 match MAME's table (core/src/roms.c) is embedded under
MAME's file name, whatever it is called locally; a .zip is looked inside.
Anything else is ignored.

usage: embed-roms.py <out.c> <dir>
       embed-roms.py --none <out.c>
"""

import sys
import zipfile
import zlib
from pathlib import Path

# (size, crc) -> MAME's file name; mirrors s_roms[] in core/src/roms.c
KNOWN = {
    (0x1000, 0x5D13730C): "7800.u7",
    (0x4000, 0xA0E10EDF): "c300558-001a.u7",
    (0x4000, 0xD5B61170): "c300558-001b.u7",
    (0x1000, 0x9BE408D3): "highscre.bin",
}

HEADER = """/* Generated by tools/roms/embed-roms.py -- do not edit.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#include "roms_embedded.h"

"""


def candidates(path):
    """The file itself, or each member of a .zip."""
    if path.suffix.lower() == ".zip":
        try:
            with zipfile.ZipFile(path) as z:
                for name in z.namelist():
                    if z.getinfo(name).file_size <= 0x4000:
                        yield z.read(name)
        except zipfile.BadZipFile:
            return
    elif path.stat().st_size <= 0x4000:
        yield path.read_bytes()


def main():
    args = sys.argv[1:]
    if args and args[0] == "--none":
        if len(args) != 2:
            sys.exit(__doc__)
        Path(args[1]).write_text(
            HEADER
            + "/* Nothing embedded -- the shipping configuration. */\n"
            + "const a7800_embedded_rom a7800_embedded_roms[1] = { { 0, 0, 0 } };\n"
            + "const unsigned a7800_embedded_rom_count = 0;\n")
        return 0

    if len(args) != 2:
        sys.exit(__doc__)
    out, src = Path(args[0]), Path(args[1])
    found = {}
    for f in sorted(src.iterdir()) if src.is_dir() else []:
        if not f.is_file():
            continue
        for data in candidates(f):
            name = KNOWN.get((len(data), zlib.crc32(data) & 0xFFFFFFFF))
            if name and name not in found:
                found[name] = data

    body = [HEADER,
            "/* WITH_A7800_ROMS=ON: a developer build. NOT redistributable.\n"
            " * See COMPLIANCE.md. */\n"]
    for i, (name, data) in enumerate(found.items()):
        body.append("static const uint8_t rom%d[%d] = {\n" % (i, len(data)))
        for j in range(0, len(data), 16):
            body.append("    " + ",".join("0x%02X" % b for b in data[j:j + 16]) + ",\n")
        body.append("};\n")
    body.append("\nconst a7800_embedded_rom a7800_embedded_roms[%d] = {\n" % max(1, len(found)))
    for i, (name, data) in enumerate(found.items()):
        body.append('    { "%s", rom%d, %d },\n' % (name, i, len(data)))
    if not found:
        body.append("    { 0, 0, 0 },\n")
    body.append("};\nconst unsigned a7800_embedded_rom_count = %d;\n" % len(found))
    out.write_text("".join(body))
    print("embed-roms: %d image(s): %s" % (len(found), ", ".join(found) or "none"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
